// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOiQngt-75gjaiiC5dHM_iQ2z17IptDLU',
    appId: '1:539293875044:web:e50288b3fa0649c7679871',
    messagingSenderId: '539293875044',
    projectId: 'test-firebase-flutter-72bf1',
    authDomain: 'test-firebase-flutter-72bf1.firebaseapp.com',
    storageBucket: 'test-firebase-flutter-72bf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJu_YyFVKJzkLUngCzFnZTwMrgB15jm10',
    appId: '1:539293875044:android:7d9459f1f435c57c679871',
    messagingSenderId: '539293875044',
    projectId: 'test-firebase-flutter-72bf1',
    storageBucket: 'test-firebase-flutter-72bf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP-fiB7W-TDatdJo_CwjtLnPaXlSq1jgU',
    appId: '1:539293875044:ios:1fd220126f46d647679871',
    messagingSenderId: '539293875044',
    projectId: 'test-firebase-flutter-72bf1',
    storageBucket: 'test-firebase-flutter-72bf1.appspot.com',
    iosClientId:
        '539293875044-muvno60sfhnss86evetdhfimju5qqdq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP-fiB7W-TDatdJo_CwjtLnPaXlSq1jgU',
    appId: '1:539293875044:ios:1fd220126f46d647679871',
    messagingSenderId: '539293875044',
    projectId: 'test-firebase-flutter-72bf1',
    storageBucket: 'test-firebase-flutter-72bf1.appspot.com',
    iosClientId:
        '539293875044-muvno60sfhnss86evetdhfimju5qqdq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.testfirebase',
  );
}
